### ISSUE TITLE
Проверка

### ISSUE THREAD

**Issue by accetone** [he1by/University#1]
Очень ёмкое название
https://github.com/he1by/University/blob/master/laba2/Interface.cs#L10

Реализуй интерфейс неявно
https://github.com/he1by/University/blob/master/laba2/Figure.cs#L16
https://github.com/he1by/University/blob/master/laba2/Figure.cs#L21

Нехватает 
- бесплодного класса
- лямбды
- as и is

**Comment by he1by** [comment]
Всё доделал : 
-интерфейс задал неявно
-лямбда теперь используется в override toString () //(для класса Figure) 
-as и is использовал в Program.cs
-бесплодный класс был же (Rectangle)
